dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
     
    path('statistics/', views.statistics, name="statistics"), 
    path('customer/<slug:slug>/',views.customer,name='customer'),
    path('productAdmin/',views.productAdminPage,name='productAdmin'),
    path('addProduct/', views.addProduct, name="addProduct"),
    path('upDataProduct/', views.upDataProduct, name="upDataProduct"),
    path('giftVoucher/', views.giftVoucher, name="giftVoucher"),
    path('addBlog/', views.addBlog, name="addBlog"),
    path('chat/', views.chat, name="chat"),
    path('statistics/char/', views.char, name="char"),
    path('productAdminDetail/<slug:slug>/',views.productAdminDetail,name='productAdminDetail'),
    path('customer/',views.listCustomer,name='listCustomer'),
    path('statistics/char/customer', views.charCustomer, name="charCustomer"),

]

ecom/urls.py
from django.urls import path

from . import views
 
urlpatterns =[
 

    path('accountSetting/',views.accountSettingPage,name='accountSetting'),
    path('changePassWord/',views.changePassWord,name='changePassWord'),
    path('',views.dashboardPage,name='home'),
    
    path('user/', views.home, name='user-page'),
    path('about/',views.aboutPage,name='about'),
    path('contact/', views.contactPage, name='contact'),
    path('home2/', views.home2Page, name='home2'),
    path('home3/', views.home3Page, name='home3'),
    path('add_cart_item/', views.addCartItem, name="addCartItem"),
    
     
    
    path('add_favorite/', views.addFavorite, name="addFavorite"),
     

    path('totalItemList/', views.totalItemList, name="totalItemList"),

    
    path('ordetItemList/', views.orderList, name="orderList"),
    path('productList/', views.productList, name="productList"),

    path('list/', views.list, name="list"),

 
]

ecommerce3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom.urls')),
    path('',include('dashboard.urls')),
    path('',include('chat.urls')),
    path('',include('Product.urls')),
    path('',include('register.urls')),
    path('',include('pay.urls')),
    path('',include('blog.urls')),
]            
urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path

from . import views
app_name='pay'
urlpatterns =[
    path('shopingCart/',views.shopingcartPage,name='shopingCart'),
    path('discount/', views.discount, name="discount"),
    path('process_order/', views.processOrder, name="processOrder"),
    path('exchange/', views.exchange, name="exchange"),
  
]

ecom/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.views.generic import ListView
from django.conf import settings

from datetime import timedelta

from django.core.paginator import Paginator

from rest_framework.decorators import api_view
from rest_framework.response import Response

from chat.models import *
from dashboard.models import *


import re
from dashboard.urls import *
import json
import datetime
from .decorators import unauthenticated_user, allowed_users, admin_only
from .form import CustomerForm,ChangePassWordForm
from .utils import cartData,ecommerce3Product
from .filter import productFilter
from pay.models import *
# Create your views here.
@login_required(login_url='login')
@admin_only
def dashboardPage(request):
    customer = Customer.objects.all()
    numberUser = customer.count()
    data = Data.objects.all().filter(complete=True).order_by("-date_complete")
    myFilter = productFilter(request.GET,queryset=data)
    data = myFilter.qs
    date = LoginAttempts.objects.all() 
    total = 0
    for item in data:
        total += item.product.price * item.quantity
    
    room = Room.objects.all()
    paginator = Paginator(data, 10)
    page = request.GET.get('page', 1)
    try:
        products_paged = paginator.page(page)
    except PageNotAnInteger:
        products_paged = paginator.page(1)
    except EmptyPage:
        products_paged = paginator.page(paginator.num_pages)
     
    context = {'data':products_paged,'room':room,'customer':customer,'numberUser':numberUser,'total':total,'myFilter': myFilter}
    return render(request, 'admin/dashboard.html', context)
 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def changePassWord(request):
    form = ChangePassWordForm()
    customer1 = request.user.customer
    customer = request.user
     
    if request.method == 'POST':
        form = ChangePassWordForm(request.POST)     
        if form.is_valid():
            currentPassword = form.cleaned_data.get('currentPassword')
            newPassword = form.cleaned_data.get('newPassword')
            confirmPassword=form.cleaned_data.get('confirmPassword')
            print("username",currentPassword)
            if customer.check_password(currentPassword):
                while True:  
                    if (len(newPassword)<8):
                        flag = -1
                        break
                    elif not re.search("[a-z]", newPassword):
                        flag = -1
                        break
                    elif not re.search("[A-Z]", newPassword):
                        flag = -1
                        break
                    elif not re.search("[0-9]", newPassword):
                        flag = -1
                        break
                    else:
                        flag = 0
                        print("Valid Password")
                        break 
                if flag ==0:
                    if  newPassword == confirmPassword:
                        print("customer1:",customer1)
                        old = oldPassWord.objects.all().filter(customer= customer1)
                        print("old:",old)
                        for password in old:
                            print("old1:",password.oldPassWord)
                            if password.oldPassWord == newPassword:
                                flag=2
                                messages.info(request, 'Is the same as the old password')
                                break
                        if flag !=2:
                            oldPassWord.objects.create(
                                customer=customer1,
                                oldPassWord= currentPassword
                            )
                            customer.set_password(newPassword)
                            customer.save()
                            messages.info(request, 'Updated Password')
                            return redirect('login')
                else:
                    messages.info(request, 'Invalid password')
            else:
                messages.info(request, 'wrong password')
    print("user:")
    print("user1:",request.user.password)
    context = {'form': form}
    return render(request,'pages/changePassWord.html',context)



@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def aboutPage(request):
    products = Product.objects.all()
    customer = request.user.customer
    item, create = Order.objects.get_or_create(customer=customer)
    favorite1 ,create = Favorite.objects.get_or_create(customer= customer)
    favorite = favorite1.favoriteproduct_set.all()
    order =item.orderitem_set.all()
    for item2 in favorite:
        for item1 in products:
            if item1.name == item2.product.name:
                item1.favorite =1
    sum=0
    for item3 in products:
        if item3.favorite==1:
            sum+=1
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/about.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def contactPage(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/contact.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home2Page(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/home2.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home3Page(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/home3.html', context)

from datetime import timedelta 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home(request):
    
   
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    sum1 = len(Product.TAGS)
    
    tag ={}
    for i in range(sum1):
        tag[i]= Product.TAGS[i][1]
    type ={}
    sum2 = len(Product.TYPE)
    for i in range(sum2):
        type[i]= Product.TYPE[i][1]
    if request.is_ajax():
        print("hi")
        a=request.POST.get('e')
        print("a:",a)
        if str(a)=="low_to_high":
            products = Product.objects.all().filter().order_by("price")
        elif str(a)=="high_to_low":
            products = Product.objects.all().filter().order_by("-price")
        elif str(a)=="default":
            products = Product.objects.all()
        elif str(a)=="popularity":
            products = Product.objects.all().filter().order_by("-sold")
        context = {"products": products,'order':order,'item':item,'favorite':favorite,'sum':sum, 'tag':tag,'type':type}
        return render(request, 'product/productAjax.html', context)
    context = { 'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum,'tag':tag,'type':type}
    return render(request, 'pages/index.html', context)


 

from django.forms.models import model_to_dict
from django.core import serializers
def addCartItem(request):
    if request.is_ajax():
        productId=request.POST.get('productId')
        action=request.POST.get('action')
        customer = request.user.customer
        product = Product.objects.get(id=productId)
         
        size=request.POST.get('size')
        color=request.POST.get('color')
        print("actin:",action)
        order, created = Order.objects.get_or_create(customer=customer)
        total = order.get_total_item()
        quantity = order.get_total_order()
        change=1
        if product.amout ==0 :
            change = 0
        if action == "create":
            value=int(request.POST.get('value'))
             
            product.amout = float(product.amout)-float(value)
            product.save()
            try:
                OrderItems = OrderItem.objects.get(order=order,product=product,size = size , color = color)
            except OrderItem.DoesNotExist:
                OrderItems = None
            if OrderItems is None:
                OrderItems =OrderItem.objects.create(
                    order=order,
                    product = product,
                    quantity=value,
                    size =size,
                    color =color
                )
                OrderItems.save()
            else:
                OrderItems.quantity =OrderItems.quantity + value
                OrderItems.save()
            orderItem = OrderItem.objects.filter(order = order)
            quantity = quantity +value
            
        else :
            
            if size=="M":

ecom/templates/char/char.html
<!DOCTYPE html>
<html>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<body>
<div class="container">
    <div class="row">
        <div  class="col-7">
                <div style="padding-bottom: 50px;"></div>
                <div id="myPlot"style="width:100%;max-width:900px;"></div> 
        </div>
        <div  class="col-5">
            <a href="{%url 'dashboard:charCustomer' %}" style="text-align: center;"><h4>Top customer</h4> </a> 
            <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">No</th>
                    <th scope="col">Name</th>
                    <th scope="col">Cost</th>
                  </tr>
                </thead>
                {% for name ,cost in top %}
                <tbody >
                  <tr>
                    <th>{{ forloop.counter }}</th> 
                    <th><a href="{{name.get_absolute_url}}">{{name}}</a></th>
                    <td>{{cost}} $</td>
                  </tr>
                  </tr>
                </tbody>
                {% endfor%}
              </table>
        </div>
    </div>
    </br>    
    <div class="row">
      <div  class="col-7">
              <div style="padding-bottom: 50px;"></div>
              <div id="myPlot1"style="width:100%;max-width:900px;"></div> 
      </div> 
      <div  class="col-5">
          <div style="text-align: center;"><h4>Top Product</h4> </div> 
          <table class="table table-dark">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Name</th>
                  <th scope="col">Quantity</th>
                </tr>
              </thead>
              {% for name ,cost in amount %}
              <tbody>
                <tr>
                  <th>{{ forloop.counter }}</th> 
                  <th><a href="{% url 'dashboard:productAdminDetail' name.slug %}">{{name}}</a></th>
                  <td>{{cost}}</td>
                </tr>
                </tr>
              </tbody>
              {% endfor%}
            </table>
      </div>
  </div>
  <div >
    <div class="row">    
        <div class="row">
            <canvas class="col-8"  id="myChart" style="width:100%;max-width:800px"></canvas>
            <div class="col-4">3</div>
        </div>
    </div>
</div>
<div id="myPlot2" style="width:100%;max-width:700px"></div>
</div>
<script>  
    var xArray = [];
    var yArray = [];
    {% for name ,x in sell.items %}
        xArray.push("{{name}}");
        yArray.push({{x}});
    {% endfor%}
    console.log("x:",xArray)
    console.log("y:",yArray)
    var layout = {title:"Revenue Per Product"};

    var data = [{labels:xArray, values:yArray, type:"pie"}];

    Plotly.newPlot("myPlot", data, layout);
</script>
<script>
    var xMonth = [];
    var profit =[];
    var cost=[];
    var revenue=[];
    {% for i in income%}
        xMonth.push("{{i.data_create.year}}-{{i.data_create.month}}");
        profit.push({{i.total_profit}});
        cost.push({{i.total_cost}});
        revenue.push({{i.total_revenue}});
    {%endfor%}
    new Chart("myChart", {
      type: "line",
      data: {
        labels: xMonth,
        datasets: [{ 
          data: profit,
          borderColor: "red",
          fill: false,
          label: 'Profit',
        }, { 
          data: cost,
          borderColor: "green",
          fill: false,
          label: 'Cost',
        }, { 
          data: revenue,
          borderColor: "blue",
          fill: false,
          label: 'Revenue',
        }]
      },
      options: {
        legend: {display: true}
      }
    });
</script>
<script>  
  var xArray = [];
  var yArray = [];
  {% for name ,x in amount %}
      xArray.push("{{name}}");
      yArray.push({{x}});
  {% endfor%}
  console.log("x:",xArray)
  console.log("y:",yArray)
  var layout = {title:"Amount Per Product"};

  var data = [{labels:xArray, values:yArray, type:"pie"}];

  Plotly.newPlot("myPlot1", data, layout);
</script> 
<script>
  var xArray = [];
  var yArray = [];
  {% for name,amount in address%}
        xArray.push("{{name}}");
        yArray.push({{amount}});
  {%endfor%}
  var data = [{
    x:xArray,
    y:yArray,
    type:"bar"
  }];
  
  var layout = {title:"World Wide Wine Production"};
  
  Plotly.newPlot("myPlot2", data, layout);
  </script>
</body>
</html>
 
 

ecom/templates/char/charCustomer.html
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">...</div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">...</div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
  </div>