Product/urls.py
from . import views
from django.urls import path
app_name='Product'
    
urlpatterns = [
    path('product/<slug:slug>/',views.productDetailPage,name='product_detail'),
    path('product/',views.productPage,name='product'),
    path('quickView/',views.quickView,name='quickView'),
    path('product/sortBy/<slug:slug>/',views.productSortBy,name='productSortBy'),
   
]

ecom/urls.py
from django.urls import path

from . import views
 
urlpatterns =[
 

    path('accountSetting/',views.accountSettingPage,name='accountSetting'),
    path('changePassWord/',views.changePassWord,name='changePassWord'),
    path('',views.dashboardPage,name='home'),
    
    path('user/', views.home, name='user-page'),
    path('about/',views.aboutPage,name='about'),
    path('contact/', views.contactPage, name='contact'),
    path('home2/', views.home2Page, name='home2'),
    path('home3/', views.home3Page, name='home3'),
    path('add_cart_item/', views.addCartItem, name="addCartItem"),
    
     
    
    path('add_favorite/', views.addFavorite, name="addFavorite"),
     

    path('totalItemList/', views.totalItemList, name="totalItemList"),

    
    path('ordetItemList/', views.orderList, name="orderList"),
    path('productList/', views.productList, name="productList"),

    path('list/', views.list, name="list"),

 
]

ecommerce3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom.urls')),
    path('',include('dashboard.urls')),
    path('',include('chat.urls')),
    path('',include('Product.urls')),
    path('',include('register.urls')),
    path('',include('pay.urls')),
    path('',include('blog.urls')),
]            
urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path

from . import views
app_name='pay'
urlpatterns =[
    path('shopingCart/',views.shopingcartPage,name='shopingCart'),
    path('discount/', views.discount, name="discount"),
    path('process_order/', views.processOrder, name="processOrder"),
    path('exchange/', views.exchange, name="exchange"),
  
]

ecom/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.views.generic import ListView
from django.conf import settings

from datetime import timedelta

from django.core.paginator import Paginator

from rest_framework.decorators import api_view
from rest_framework.response import Response

from chat.models import *
from dashboard.models import *


import re
from dashboard.urls import *
import json
import datetime
from .decorators import unauthenticated_user, allowed_users, admin_only
from .form import CustomerForm,ChangePassWordForm
from .utils import cartData,ecommerce3Product
from .filter import productFilter
from pay.models import *
# Create your views here.
@login_required(login_url='login')
@admin_only
def dashboardPage(request):
    customer = Customer.objects.all()
    numberUser = customer.count()
    data = Data.objects.all().filter(complete=True).order_by("-date_complete")
    myFilter = productFilter(request.GET,queryset=data)
    data = myFilter.qs
    date = LoginAttempts.objects.all() 
    total = 0
    for item in data:
        total += item.product.price * item.quantity
    
    room = Room.objects.all()
    paginator = Paginator(data, 10)
    page = request.GET.get('page', 1)
    try:
        products_paged = paginator.page(page)
    except PageNotAnInteger:
        products_paged = paginator.page(1)
    except EmptyPage:
        products_paged = paginator.page(paginator.num_pages)
     
    context = {'data':products_paged,'room':room,'customer':customer,'numberUser':numberUser,'total':total,'myFilter': myFilter}
    return render(request, 'admin/dashboard.html', context)
 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def changePassWord(request):
    form = ChangePassWordForm()
    customer1 = request.user.customer
    customer = request.user
     
    if request.method == 'POST':
        form = ChangePassWordForm(request.POST)     
        if form.is_valid():
            currentPassword = form.cleaned_data.get('currentPassword')
            newPassword = form.cleaned_data.get('newPassword')
            confirmPassword=form.cleaned_data.get('confirmPassword')
            print("username",currentPassword)
            if customer.check_password(currentPassword):
                while True:  
                    if (len(newPassword)<8):
                        flag = -1
                        break
                    elif not re.search("[a-z]", newPassword):
                        flag = -1
                        break
                    elif not re.search("[A-Z]", newPassword):
                        flag = -1
                        break
                    elif not re.search("[0-9]", newPassword):
                        flag = -1
                        break
                    else:
                        flag = 0
                        print("Valid Password")
                        break 
                if flag ==0:
                    if  newPassword == confirmPassword:
                        print("customer1:",customer1)
                        old = oldPassWord.objects.all().filter(customer= customer1)
                        print("old:",old)
                        for password in old:
                            print("old1:",password.oldPassWord)
                            if password.oldPassWord == newPassword:
                                flag=2
                                messages.info(request, 'Is the same as the old password')
                                break
                        if flag !=2:
                            oldPassWord.objects.create(
                                customer=customer1,
                                oldPassWord= currentPassword
                            )
                            customer.set_password(newPassword)
                            customer.save()
                            messages.info(request, 'Updated Password')
                            return redirect('login')
                else:
                    messages.info(request, 'Invalid password')
            else:
                messages.info(request, 'wrong password')
    print("user:")
    print("user1:",request.user.password)
    context = {'form': form}
    return render(request,'pages/changePassWord.html',context)



@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def aboutPage(request):
    products = Product.objects.all()
    customer = request.user.customer
    item, create = Order.objects.get_or_create(customer=customer)
    favorite1 ,create = Favorite.objects.get_or_create(customer= customer)
    favorite = favorite1.favoriteproduct_set.all()
    order =item.orderitem_set.all()
    for item2 in favorite:
        for item1 in products:
            if item1.name == item2.product.name:
                item1.favorite =1
    sum=0
    for item3 in products:
        if item3.favorite==1:
            sum+=1
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/about.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def contactPage(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/contact.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home2Page(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/home2.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home3Page(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/home3.html', context)

from datetime import timedelta 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home(request):
    
   
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    sum1 = len(Product.TAGS)
    
    tag ={}
    for i in range(sum1):
        tag[i]= Product.TAGS[i][1]
    type ={}
    sum2 = len(Product.TYPE)
    for i in range(sum2):
        type[i]= Product.TYPE[i][1]
    if request.is_ajax():
        print("hi")
        a=request.POST.get('e')
        print("a:",a)
        if str(a)=="low_to_high":
            products = Product.objects.all().filter().order_by("price")
        elif str(a)=="high_to_low":
            products = Product.objects.all().filter().order_by("-price")
        elif str(a)=="default":
            products = Product.objects.all()
        elif str(a)=="popularity":
            products = Product.objects.all().filter().order_by("-sold")
        context = {"products": products,'order':order,'item':item,'favorite':favorite,'sum':sum, 'tag':tag,'type':type}
        return render(request, 'product/productAjax.html', context)
    context = { 'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum,'tag':tag,'type':type}
    return render(request, 'pages/index.html', context)


 

from django.forms.models import model_to_dict
from django.core import serializers
def addCartItem(request):
    if request.is_ajax():
        productId=request.POST.get('productId')
        action=request.POST.get('action')
        customer = request.user.customer
        product = Product.objects.get(id=productId)
         
        size=request.POST.get('size')
        color=request.POST.get('color')
        print("actin:",action)
        order, created = Order.objects.get_or_create(customer=customer)
        total = order.get_total_item()
        quantity = order.get_total_order()
        change=1
        if product.amout ==0 :
            change = 0
        if action == "create":
            value=int(request.POST.get('value'))
             
            product.amout = float(product.amout)-float(value)
            product.save()
            try:
                OrderItems = OrderItem.objects.get(order=order,product=product,size = size , color = color)
            except OrderItem.DoesNotExist:
                OrderItems = None
            if OrderItems is None:
                OrderItems =OrderItem.objects.create(
                    order=order,
                    product = product,
                    quantity=value,
                    size =size,
                    color =color
                )
                OrderItems.save()
            else:
                OrderItems.quantity =OrderItems.quantity + value
                OrderItems.save()
            orderItem = OrderItem.objects.filter(order = order)
            quantity = quantity +value
            
        else :
            
            if size=="M":

ecom/templates/pages/about.html
{%  extends 'pages/main.html' %}

{% block content %}{% load static%}
	<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('images/bg-01.jpg');">
		<h2 class="ltext-105 cl0 txt-center">
			About
		</h2>
	</section>	


	<!-- Content page -->
	<section class="bg0 p-t-75 p-b-120">
		<div class="container">
			<div class="row p-b-148">
				<div class="col-md-7 col-lg-8">
					<div class="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
						<h3 class="mtext-111 cl2 p-b-16">
							Our Story
						</h3>

						<p class="stext-113 cl6 p-b-26">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris consequat consequat enim, non auctor massa ultrices non. Morbi sed odio massa. Quisque at vehicula tellus, sed tincidunt augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas varius egestas diam, eu sodales metus scelerisque congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas gravida justo eu arcu egestas convallis. Nullam eu erat bibendum, tempus ipsum eget, dictum enim. Donec non neque ut enim dapibus tincidunt vitae nec augue. Suspendisse potenti. Proin ut est diam. Donec condimentum euismod tortor, eget facilisis diam faucibus et. Morbi a tempor elit.
						</p>

						<p class="stext-113 cl6 p-b-26">
							Donec gravida lorem elit, quis condimentum ex semper sit amet. Fusce eget ligula magna. Aliquam aliquam imperdiet sodales. Ut fringilla turpis in vehicula vehicula. Pellentesque congue ac orci ut gravida. Aliquam erat volutpat. Donec iaculis lectus a arcu facilisis, eu sodales lectus sagittis. Etiam pellentesque, magna vel dictum rutrum, neque justo eleifend elit, vel tincidunt erat arcu ut sem. Sed rutrum, turpis ut commodo efficitur, quam velit convallis ipsum, et maximus enim ligula ac ligula. 
						</p>

						<p class="stext-113 cl6 p-b-26">
							Any questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on (+1) 96 716 6879
						</p>
					</div>
				</div>

				<div class="col-11 col-md-5 col-lg-4 m-lr-auto">
					<div class="how-bor1 ">
						<div class="hov-img0">
							<img src="{% static 'images/about-01.jpg' %} " alt="IMG">
						</div>
					</div>
				</div>
			</div>
			
			<div class="row">
				<div class="order-md-2 col-md-7 col-lg-8 p-b-30">
					<div class="p-t-7 p-l-85 p-l-15-lg p-l-0-md">
						<h3 class="mtext-111 cl2 p-b-16">
							Our Mission
						</h3>

						<p class="stext-113 cl6 p-b-26">
							Mauris non lacinia magna. Sed nec lobortis dolor. Vestibulum rhoncus dignissim risus, sed consectetur erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam maximus mauris sit amet odio convallis, in pharetra magna gravida. Praesent sed nunc fermentum mi molestie tempor. Morbi vitae viverra odio. Pellentesque ac velit egestas, luctus arcu non, laoreet mauris. Sed in ipsum tempor, consequat odio in, porttitor ante. Ut mauris ligula, volutpat in sodales in, porta non odio. Pellentesque tempor urna vitae mi vestibulum, nec venenatis nulla lobortis. Proin at gravida ante. Mauris auctor purus at lacus maximus euismod. Pellentesque vulputate massa ut nisl hendrerit, eget elementum libero iaculis.
						</p>

						<div class="bor16 p-l-29 p-b-9 m-t-22">
							<p class="stext-114 cl6 p-r-40 p-b-11">
								Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while.
							</p>

							<span class="stext-111 cl8">
								- Steve Job’s 
							</span>
						</div>
					</div>
				</div>

				<div class="order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30">
					<div class="how-bor2">
						<div class="hov-img0">
							<img src="images/about-02.jpg" alt="IMG">
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>	
	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>
{% endblock content %}

ecom/templates/pages/accounts_setting.html
{%  extends 'pages/main.html' %}
{% load static %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >
		
		</div>
	</div>
	<div class="col-md-7">
		<div class="card card-body">
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
                {{form}}
		
			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
		 
	</div>
	<div class="col-md-2">
		<a href="{%url 'changePassWord' %}">ChangePassWord</a>
	</div>
</div>



{% endblock %}

ecom/templates/pages/cart.html
{% load static%}
<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart"  >
		<div class="s-full js-hide-cart"></div>
		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll"  id="ajax_cart" >
					{%for item in order%}
						<ul class="header-cart-wrapitem w-full">
							<li class="header-cart-item flex-w flex-t m-b-12">
								<div data-product="{{item.product.id}}" data-action="erase" class="header-cart-item-img update-cart">
									<img src="{{item.product.imageURL}}" alt="IMG">
								</div>

								<div class="header-cart-item-txt p-t-8">
									<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
										{{item.product.name}}
									</a>

									<span class="header-cart-item-info">
										{{item.quantity}} x {{item.product.price}}
									</span>
								</div>
							</li>
						</ul>
					{% endfor %}
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: ${{item.get_total_item}}
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{% url 'pay:shopingCart'  %} " class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a> 

						<a href="{% url 'pay:shopingCart'  %} " class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>

ecom/templates/pages/changePassWord.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
        .pass_show{position: relative} 

        .pass_show .ptxt { 

            position: absolute; 

            top: 50%; 

            right: 10px; 

            z-index: 1; 

            color: #f36c01; 

            margin-top: -10px; 

            cursor: pointer; 

            transition: .3s ease all; 

        } 
        .pass_show .ptxt:hover{color: #333333;} 
</style>
<div class="container">
	<div class="row">
		<div class="col-sm-4">
		    <form method="POST" action="" enctype="multipart/form-data"> 
                {% csrf_token%}
                <label>Current Password</label>
                <div class="form-group pass_show"> 
                    {{form.currentPassword}}
                </div> 
                <label>New Password</label>
                <div class="form-group pass_show"> 
                    {{form.newPassword}} 
                </div> 
                <label>Confirm Password</label>
                <div class="form-group pass_show"> 
                    {{form.confirmPassword}}
                </div> 
                <div class="d-flex justify-content-center mt-3 login_container">
                    <input class="btn login_btn" type="submit" value="submit">
                    {% for message in messages %}
                        <p id="messages">{{message}}</p>
                    {% endfor %}
                </div>
            </form>
            
		</div>  
	</div>
</div>
<script>
    $(document).ready(function(){
        $('.pass_show').append('<span class="ptxt">Show</span>');  
    });
    $(document).on('click','.pass_show .ptxt', function(){ 

        $(this).text($(this).text() == "Show" ? "Hide" : "Show"); 

        $(this).prev().attr('type', function(index, attr){return attr == 'password' ? 'text' : 'password'; }); 

    });  
</script>

ecom/templates/pages/favorite.html
{% load static%}
	<div class="wrap-header-cart js-panel-favorite">
		<div class="s-full js-hide-cart"></div>
		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Favorite product
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-favorite">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
                {%for item in favorite%}
				<ul class="header-cart-wrapitem w-full"  >
					<li class="header-cart-item flex-w flex-t m-b-12" >
						<div data-product="{{item.product.id}}" data-action="remove" class="header-cart-item-img add-favorite ">
							<img src="{{item.product.imageURL}}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="{{item.product.get_absolute_url}}" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								{{item.product.name}} 
							</a>
						</div>
					</li>
				</ul>
                {% endfor %}
                <div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: ${{item.get_total_item}}
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{% url 'pay:shopingCart'  %} " class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a> 

						<a href="{% url 'pay:shopingCart'  %} " class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>

	</div>

ecom/templates/pages/index.html
 
{%  extends 'pages/main.html' %}

{% block content %}{% load static %}
     
	<!-- Slider -->
	<section class="section-slide">
		<div class="wrap-slick1">
			<div class="slick1">
				<div class="item-slick1" style="background-image: url(images/slide-01.jpg);">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									Women Collection 2018
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									NEW SEASON
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
								<a href="{% url 'Product:product'  %} " class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Shop Now
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="item-slick1" style="background-image: url(images/slide-02.jpg);">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="rollIn" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									Men New-Season
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="lightSpeedIn" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									Jackets & Coats
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="slideInUp" data-delay="1600">
								<a href="{% url 'Product:product'  %} " class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Shop Now
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="item-slick1" style="background-image: url(images/slide-03.jpg);">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="rotateInDownLeft" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									Men Collection 2018
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="rotateInUpRight" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									New arrivals
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="rotateIn" data-delay="1600">
								<a href="{% url 'Product:product'  %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Shop Now
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- Banner -->
	<div class="sec-banner bg0 p-t-80 p-b-50">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
					<!-- Block1 -->
					<div class="block1 wrap-pic-w">
						<img src="images/banner-01.jpg" alt="IMG-BANNER">

						<a href="{% url 'Product:product'  %} " class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
							<div class="block1-txt-child1 flex-col-l">
								<span class="block1-name ltext-102 trans-04 p-b-8">
									Women
								</span>

								<span class="block1-info stext-102 trans-04">
									Spring 2018
								</span>
							</div>

							<div class="block1-txt-child2 p-b-4 trans-05">
								<div class="block1-link stext-101 cl0 trans-09">
									Shop Now
								</div>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Product -->
	{%  include 'product/productA.html' %}
	{% endblock content %}