blog/urls.py
from django.urls import path

from . import views
app_name='blog'
urlpatterns =[
    path('blogCategory/<slug:slug>/',views.blogCategory,name='category'),
    path('blog/<slug:slug>/',views.blogDetailPage,name='blog_detail'),
    path('blog/', views.blogPage, name='blog'),
]

ecom/urls.py
from django.urls import path

from . import views
 
urlpatterns =[
 

    path('accountSetting/',views.accountSettingPage,name='accountSetting'),
    path('changePassWord/',views.changePassWord,name='changePassWord'),
    path('',views.dashboardPage,name='home'),
    
    path('user/', views.home, name='user-page'),
    path('about/',views.aboutPage,name='about'),
    path('contact/', views.contactPage, name='contact'),
    path('home2/', views.home2Page, name='home2'),
    path('home3/', views.home3Page, name='home3'),
    path('add_cart_item/', views.addCartItem, name="addCartItem"),
    
     
    
    path('add_favorite/', views.addFavorite, name="addFavorite"),
     

    path('totalItemList/', views.totalItemList, name="totalItemList"),

    
    path('ordetItemList/', views.orderList, name="orderList"),
    path('productList/', views.productList, name="productList"),

    path('list/', views.list, name="list"),

 
]

ecommerce3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom.urls')),
    path('',include('dashboard.urls')),
    path('',include('chat.urls')),
    path('',include('Product.urls')),
    path('',include('register.urls')),
    path('',include('pay.urls')),
    path('',include('blog.urls')),
]            
urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path

from . import views
app_name='pay'
urlpatterns =[
    path('shopingCart/',views.shopingcartPage,name='shopingCart'),
    path('discount/', views.discount, name="discount"),
    path('process_order/', views.processOrder, name="processOrder"),
    path('exchange/', views.exchange, name="exchange"),
  
]

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
# Create your models here.
def create_slug(title):  # new
    slug = slugify(title)
    qs = Blog.objects.filter(slug=slug)
    if qs:
        exists = qs.exists()
        if exists:
            slug = "%s-%s" % (slug, qs.first().id)
    return slug
class Category(models.Model):
   
    name = models.CharField(max_length=2000)
    slug = models.SlugField(max_length=2000)
    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
class Blog(models.Model):
    
    name = models.CharField(max_length=100, null=True)
    data_ordered = models.DateTimeField(auto_now_add=True)
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    images1  = models.ImageField(default="null",null=True, blank=True)
    detail = models.CharField(max_length=1000,null=True)
    detail1 = models.CharField(max_length=10000,null=True)
    slug = models.SlugField(max_length=2000)


    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = create_slug(self.name)
        return super().save(*args, **kwargs)
    def __str__(self):
        return str(self.name)
    @property
    def imageURL(self):
        try:
            url = self.images1.url
        except:
            url = ''
        return url

blog/views.py
from django.shortcuts import render 
from .models import *
 
from django.contrib.auth.decorators import login_required
 
from django.core.paginator import Paginator

 
from .decorators import  allowed_users
from .utils import cartData,ecommerce3Product
 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def blogDetailPage(request,slug):
    data      = cartData(request,slug)
    category = Category.objects.all()
    products  = data['products']
    order     = data['order']
    blogs     = data['blogs']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'category':category,'products':products,'order':order,'blogs':blogs,'item':item,'favorite':favorite,'sum':sum}
    
    return render(request, 'blog/blog-detail.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def blogPage(request):
    category = Category.objects.all()
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    blogs     = data['blogs']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page', 1)
    try:
        blog_paged = paginator.page(page)
    except PageNotAnInteger:
        blog_paged = paginator.page(1)
    except EmptyPage:
        blog_paged = paginator.page(paginator.num_pages)
    context = {'products':products,'order':order,'blogs':blog_paged,'item':item,'favorite':favorite,'sum':sum,'category':category}
    return render(request, 'blog/blog.html', context)

def blogCategory(request,slug):
    category = Category.objects.all()
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    print("slugP:",slug)
    categorys=Category.objects.get(slug= slug)
    print("ca:",categorys)
    blogs=Blog.objects.all().filter(category=categorys)
    print("ca:",blogs)
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page', 1)
    try:
        blog_paged = paginator.page(page)
    except PageNotAnInteger:
        blog_paged = paginator.page(1)
    except EmptyPage:
        blog_paged = paginator.page(paginator.num_pages)
    context = {'blogs':blog_paged,'order':order,'item':item,'favorite':favorite,'sum':sum,'category':category}

    return render(request, 'blog/blog.html', context)


ecom/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.views.generic import ListView
from django.conf import settings

from datetime import timedelta

from django.core.paginator import Paginator

from rest_framework.decorators import api_view
from rest_framework.response import Response

from chat.models import *
from dashboard.models import *


import re
from dashboard.urls import *
import json
import datetime
from .decorators import unauthenticated_user, allowed_users, admin_only
from .form import CustomerForm,ChangePassWordForm
from .utils import cartData,ecommerce3Product
from .filter import productFilter
from pay.models import *
# Create your views here.
@login_required(login_url='login')
@admin_only
def dashboardPage(request):
    customer = Customer.objects.all()
    numberUser = customer.count()
    data = Data.objects.all().filter(complete=True).order_by("-date_complete")
    myFilter = productFilter(request.GET,queryset=data)
    data = myFilter.qs
    date = LoginAttempts.objects.all() 
    total = 0
    for item in data:
        total += item.product.price * item.quantity
    
    room = Room.objects.all()
    paginator = Paginator(data, 10)
    page = request.GET.get('page', 1)
    try:
        products_paged = paginator.page(page)
    except PageNotAnInteger:
        products_paged = paginator.page(1)
    except EmptyPage:
        products_paged = paginator.page(paginator.num_pages)
     
    context = {'data':products_paged,'room':room,'customer':customer,'numberUser':numberUser,'total':total,'myFilter': myFilter}
    return render(request, 'admin/dashboard.html', context)
 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def changePassWord(request):
    form = ChangePassWordForm()
    customer1 = request.user.customer
    customer = request.user
     
    if request.method == 'POST':
        form = ChangePassWordForm(request.POST)     
        if form.is_valid():
            currentPassword = form.cleaned_data.get('currentPassword')
            newPassword = form.cleaned_data.get('newPassword')
            confirmPassword=form.cleaned_data.get('confirmPassword')
            print("username",currentPassword)
            if customer.check_password(currentPassword):
                while True:  
                    if (len(newPassword)<8):
                        flag = -1
                        break
                    elif not re.search("[a-z]", newPassword):
                        flag = -1
                        break
                    elif not re.search("[A-Z]", newPassword):
                        flag = -1
                        break
                    elif not re.search("[0-9]", newPassword):
                        flag = -1
                        break
                    else:
                        flag = 0
                        print("Valid Password")
                        break 
                if flag ==0:
                    if  newPassword == confirmPassword:
                        print("customer1:",customer1)
                        old = oldPassWord.objects.all().filter(customer= customer1)
                        print("old:",old)
                        for password in old:
                            print("old1:",password.oldPassWord)
                            if password.oldPassWord == newPassword:
                                flag=2
                                messages.info(request, 'Is the same as the old password')
                                break
                        if flag !=2:
                            oldPassWord.objects.create(
                                customer=customer1,
                                oldPassWord= currentPassword
                            )
                            customer.set_password(newPassword)
                            customer.save()
                            messages.info(request, 'Updated Password')
                            return redirect('login')
                else:
                    messages.info(request, 'Invalid password')
            else:
                messages.info(request, 'wrong password')
    print("user:")
    print("user1:",request.user.password)
    context = {'form': form}
    return render(request,'pages/changePassWord.html',context)



@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def aboutPage(request):
    products = Product.objects.all()
    customer = request.user.customer
    item, create = Order.objects.get_or_create(customer=customer)
    favorite1 ,create = Favorite.objects.get_or_create(customer= customer)
    favorite = favorite1.favoriteproduct_set.all()
    order =item.orderitem_set.all()
    for item2 in favorite:
        for item1 in products:
            if item1.name == item2.product.name:
                item1.favorite =1
    sum=0
    for item3 in products:
        if item3.favorite==1:
            sum+=1
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/about.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def contactPage(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/contact.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home2Page(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/home2.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home3Page(request):
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    context = {'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum}
    return render(request, 'pages/home3.html', context)

from datetime import timedelta 
@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def home(request):
    
   
    data      = ecommerce3Product(request)
    products  = data['products']
    order     = data['order']
    item      = data['item']
    favorite  = data['favorite']
    sum       = data['sum']
    sum1 = len(Product.TAGS)
    
    tag ={}
    for i in range(sum1):
        tag[i]= Product.TAGS[i][1]
    type ={}
    sum2 = len(Product.TYPE)
    for i in range(sum2):
        type[i]= Product.TYPE[i][1]
    if request.is_ajax():
        print("hi")
        a=request.POST.get('e')
        print("a:",a)
        if str(a)=="low_to_high":
            products = Product.objects.all().filter().order_by("price")
        elif str(a)=="high_to_low":
            products = Product.objects.all().filter().order_by("-price")
        elif str(a)=="default":
            products = Product.objects.all()
        elif str(a)=="popularity":
            products = Product.objects.all().filter().order_by("-sold")
        context = {"products": products,'order':order,'item':item,'favorite':favorite,'sum':sum, 'tag':tag,'type':type}
        return render(request, 'product/productAjax.html', context)
    context = { 'products':products,'order':order,'item':item,'favorite':favorite,'sum':sum,'tag':tag,'type':type}
    return render(request, 'pages/index.html', context)


 

from django.forms.models import model_to_dict
from django.core import serializers
def addCartItem(request):
    if request.is_ajax():
        productId=request.POST.get('productId')
        action=request.POST.get('action')
        customer = request.user.customer
        product = Product.objects.get(id=productId)
         
        size=request.POST.get('size')
        color=request.POST.get('color')
        print("actin:",action)
        order, created = Order.objects.get_or_create(customer=customer)
        total = order.get_total_item()
        quantity = order.get_total_order()
        change=1
        if product.amout ==0 :
            change = 0
        if action == "create":
            value=int(request.POST.get('value'))
             
            product.amout = float(product.amout)-float(value)
            product.save()
            try:
                OrderItems = OrderItem.objects.get(order=order,product=product,size = size , color = color)
            except OrderItem.DoesNotExist:
                OrderItems = None
            if OrderItems is None:
                OrderItems =OrderItem.objects.create(
                    order=order,
                    product = product,
                    quantity=value,
                    size =size,
                    color =color
                )
                OrderItems.save()
            else:
                OrderItems.quantity =OrderItems.quantity + value
                OrderItems.save()
            orderItem = OrderItem.objects.filter(order = order)
            quantity = quantity +value
            
        else :
            
            if size=="M":

ecom/templates/blog/blog-detail.html
{%  extends 'pages/main.html' %}

{% block content %}{% load static%}
	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="{% url 'home'  %} " class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<a href="{% url 'blog:blog'  %}  " class="stext-109 cl8 hov-cl1 trans-04">
				Blog
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				{{blogs.name}}
			</span>
		</div>
	</div>
	<!-- Content page -->
	<section class="bg0 p-t-52 p-b-20">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
						<!--  -->
						{% include 'blog/blogDetail.html'%}
						<!--  -->
						{%  include 'blog/cmtBlog.html' %}
					</div>
				</div>

				{%  include 'blog/indexBlog.html' %}
			</div>
		</div>
	</section>	

	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>

	{% endblock content %}

ecom/templates/blog/blog.html
{% extends 'pages/main.html' %}

{% block content %}{% load static%}
	<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('images/bg-02.jpg');">
		<h2 class="ltext-105 cl0 txt-center">
			Blog
		</h2>
	</section>	


	<!-- Content page -->
	<section class="bg0 p-t-62 p-b-60">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					 
					<div class="p-r-45 p-r-0-lg">
						{% for blog in blogs%}
						<!-- item blog -->
						<div class="p-b-63">
							<a href="{{blog.get_absolute_url}} " class="hov-img0 how-pos5-parent">
								<img src="{{blog.imageURL}}" alt="IMG-BLOG">

								<div class="flex-col-c-m size-123 bg9 how-pos5">
									<span class="ltext-107 cl2 txt-center">
										{{blog.data_ordered.day}}
									</span>

									<span class="stext-109 cl3 txt-center">
										{{blog.data_ordered.month}}/{{blog.data_ordered.year}}
									</span>
								</div>
							</a>

							<div class="p-t-32">
								<h4 class="p-b-15">
									<a href="{{blog.get_absolute_url}} " class="ltext-108 cl2 hov-cl1 trans-04">
										{{blog.name}} 
									</a>
								</h4>

								<p class="stext-117 cl6">
									{{blog.detail}}
								</p>

								<div class="flex-w flex-sb-m p-t-18">
									<span class="flex-w flex-m stext-111 cl2 p-r-30 m-tb-10">
										<span>
											<span class="cl4">By</span> Admin  
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>

										<span>
											{{blog.category}}
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>

										<span>
											8 Comments
										</span>
									</span>

									<a href="{{blog.get_absolute_url}}" class="stext-101 cl2 hov-cl1 trans-04 m-tb-10">
										Continue Reading

										<i class="fa fa-long-arrow-right m-l-9"></i>
									</a>
								</div>
							</div>
						</div>
						{% endfor%}
						<!-- Pagination -->
						<div class="flex-l-m flex-w w-full p-t-10 m-lr--7">
							{% if blogs.has_previous %}
								<a href="?page=1"  class="flex-c-m how-pagination1 trans-04 m-all-7">1</a>
								<a href="?page={{ blogs.previous_page_number }}"  class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1">
									{{blogs.previous_page_number}}
								</a>
							{% endif %}
							{% if blogs.has_next %}
							<a  href="?page={{ blogs.next_page_number }}" class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1">
								{{blogs.next_page_number}}
							</a>
							{% endif %}
							 
						</div>
					</div>
					 
				</div>

				{%  include 'blog/indexBlog.html' %}
			</div>
		</div>
	</section>	
	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>
	{% endblock content %}

ecom/templates/blog/blogDetail.html
{% load static%}
 
<div class="wrap-pic-w how-pos5-parent">
    <img src="{{blogs.imageURL}}" alt="IMG-BLOG">

    <div class="flex-col-c-m size-123 bg9 how-pos5">
        <span class="ltext-107 cl2 txt-center">
            {{blogs.data_ordered.day}} 
        </span>

        <span class="stext-109 cl3 txt-center">
            {{blogs.data_ordered.month}} /{{blogs.data_ordered.year}} 
        </span>
    </div>
</div>

<div class="p-t-32">
    <span class="flex-w flex-m stext-111 cl2 p-b-19">
        <span>
            <span class="cl4">By</span> Admin  
            <span class="cl12 m-l-4 m-r-6">|</span>
        </span>

        <span>
            {{blogs.data_ordered.day}} {{blogs.data_ordered.month}},{{blogs.data_ordered.year}}
            <span class="cl12 m-l-4 m-r-6">|</span>
        </span>

        <span>
            {{blogs.tag}},{{blogs.categories}}, Couple  
            <span class="cl12 m-l-4 m-r-6">|</span>
        </span>

        <span>
            8 Comments
        </span>
    </span>

    <h4 class="ltext-109 cl2 p-b-28">
        {{blogs.name}}
    </h4>

    <p class="stext-117 cl6 p-b-26">
        {{blogs.detail}}
    </p>

    <p class="stext-117 cl6 p-b-26">
        {{blogs.detail1}}
    </p>
</div>

<div class="flex-w flex-t p-t-16">
    <span class="size-216 stext-116 cl8 p-t-4">
        Tags
    </span>

    <div class="flex-w size-217">
        <a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
            {{blogs.tag}}
        </a>
    </div>
</div>

ecom/templates/blog/cmtBlog.html
{% load static%}
<div class="p-t-40">
    <h5 class="mtext-113 cl2 p-b-12">
        Leave a Comment
    </h5>

    <p class="stext-107 cl6 p-b-40">
        Your email address will not be published. Required fields are marked *
    </p>

    <form>
        <div class="bor19 m-b-20">
            <textarea class="stext-111 cl2 plh3 size-124 p-lr-18 p-tb-15" name="cmt" placeholder="Comment..."></textarea>
        </div>

        <div class="bor19 size-218 m-b-20">
            <input class="stext-111 cl2 plh3 size-116 p-lr-18" type="text" name="name" placeholder="Name *">
        </div>

        <div class="bor19 size-218 m-b-20">
            <input class="stext-111 cl2 plh3 size-116 p-lr-18" type="text" name="email" placeholder="Email *">
        </div>

        <div class="bor19 size-218 m-b-30">
            <input class="stext-111 cl2 plh3 size-116 p-lr-18" type="text" name="web" placeholder="Website">
        </div>

        <button class="flex-c-m stext-101 cl0 size-125 bg3 bor2 hov-btn3 p-lr-15 trans-04">
            Post Comment
        </button>
    </form>
</div>

ecom/templates/blog/indexBlog.html
{% load static%}
<div class="col-md-4 col-lg-3 p-b-80">
    <div class="side-menu">
        <div class="bor17 of-hidden pos-relative">
            <input class="stext-103 cl2 plh4 size-116 p-l-28 p-r-55" type="text" name="search" placeholder="Search">

            <button class="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
                <i class="zmdi zmdi-search"></i>
            </button>
        </div>

        <div class="p-t-55">
            <h4 class="mtext-112 cl2 p-b-33">
                Categories
            </h4>

            <ul>
                {% for i in category%}
                <li class="bor18">
                    <a href="{{i.get_absolute_url}}" class="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
                        {{i.name}}
                    </a>
                </li>
                {% endfor%}
            </ul>
        </div>
    </div>
</div>